#!/usr/bin/env python3
"""Pin the public Biohub notebook and inject a reproducible experiment preset."""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KERNEL = "kaiwalyaatulraut/biohub-competition-solution"
API_URL = f"https://www.kaggle.com/api/v1/kernels/pull/{KERNEL}"
OUTPUT = ROOT / "notebooks" / "biohub_anchor.ipynb"
LOCK = ROOT / "public_anchor.lock.json"

PRESET = {
    "BIOHUB_DET_THRESHOLD": "0.97",
    "BIOHUB_OUTPUT_FILTER_SHORT_TRACKS": "1",
    "BIOHUB_OUTPUT_MIN_TRACK_LEN": "6",
    "BIOHUB_OUTPUT_KEEP_DIVISION_COMPONENTS": "1",
    "BIOHUB_ADAPTIVE_SHORT_TRACK_RESCUE": "0",
    "BIOHUB_MOTION_RELINK_LEARNED_BONUS": "1.0",
    "BIOHUB_SHORT_TRACK_RESCUE_TRIGGER_REMOVED_FRAC": "0.10",
    "BIOHUB_SHORT_TRACK_RESCUE_MIN_LEN": "4",
    "BIOHUB_SHORT_TRACK_RESCUE_MIN_MEAN_EDGE_PROB": "0.82",
    "BIOHUB_SHORT_TRACK_RESCUE_MAX_MEAN_EDGE_DIST_UM": "3.25",
    "BIOHUB_SHORT_TRACK_RESCUE_MAX_NODES_FRAC": "0.018",
    "BIOHUB_SHORT_TRACK_RESCUE_MAX_NODES_ABS": "180",
    "BIOHUB_GAP_CLOSE_MAX_GAP": "2",
    "BIOHUB_OUTPUT_GAP2_RECOVERY": "0",
    "BIOHUB_SAFE_DIV_MAX_UM": "4.66",
    "BIOHUB_SAFE_DIV_SISTER_MAX_UM": "7.05",
    "BIOHUB_SAFE_DIV_EXISTING_CHILD_MAX_UM": "7.65",
    "BIOHUB_SAFE_DIV_FRAME_FRAC_CAP": "0.0076",
    "BIOHUB_SAFE_DIV_GLOBAL_FRAC_CAP": "0.00375",
    "BIOHUB_USE_DEEPCENTER_VETO": "0",
    "BIOHUB_RUN_VISUAL_EDA": "0",
    "BIOHUB_RUN_OUTPUT_DIAGNOSTICS": "1",
}


def isolate_final_prediction_output(notebook: dict) -> None:
    """Keep unrelated graphs out of the final submission graph set."""
    old_run = 'subprocess.run(predict_cmd, cwd=REPO_DIR, env={**os.environ, "PYTHONPATH": "src"}, check=True)'
    new_run = '''final_prediction_env = {
    **os.environ,
    "USER": "biohub_submission",
    "USERNAME": "biohub_submission",
    "PYTHONPATH": "src",
}
subprocess.run(predict_cmd, cwd=REPO_DIR, env=final_prediction_env, check=True)'''
    old_glob = 'geffs = sorted((REPO_DIR / "predictions").glob(f"*/{METHOD}/split_0/*.geff"))'
    new_glob = '''final_predictions_dir = REPO_DIR / "predictions" / "biohub_submission" / METHOD / "split_0"
geffs = sorted(final_predictions_dir.glob("*.geff"))'''

    found_run = found_glob = False
    for cell in notebook["cells"]:
        source = "".join(cell.get("source", []))
        if old_run in source:
            source = source.replace(old_run, new_run, 1)
            found_run = True
        elif new_run in source:
            found_run = True
        if old_glob in source:
            source = source.replace(old_glob, new_glob, 1)
            found_glob = True
        elif new_glob in source:
            found_glob = True
        cell["source"] = source.splitlines(keepends=True)
    if not found_run or not found_glob:
        raise RuntimeError("Could not isolate final prediction output")


def fetch() -> tuple[dict, dict]:
    request = urllib.request.Request(API_URL, headers={"User-Agent": "biohub-anchor/1"})
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.load(response)
    return json.loads(payload["blob"]["source"]), payload["metadata"]


def preset_cell(version: int) -> dict:
    lines = [
        "# Local reproducible preset; generated by scripts/sync_public_anchor.py\n",
        "import os\n",
        "BIOHUB_PRESET = 'v31_standard_plus_global_shift'\n",
        "BIOHUB_SCORE_AXIS = 'fixed 0.97 V31-style anchor with an optional global-shift relinker'\n",
        f"BIOHUB_UPSTREAM_KERNEL = {KERNEL!r}\n",
        f"BIOHUB_UPSTREAM_VERSION = {version}\n",
    ]
    lines.extend(f"os.environ[{key!r}] = {value!r}\n" for key, value in PRESET.items())
    lines.append("print('Biohub anchor preset loaded:', BIOHUB_UPSTREAM_VERSION)\n")
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true", help="accept a newer upstream version")
    args = parser.parse_args()

    if OUTPUT.exists() and "submission_global_shift.csv" in OUTPUT.read_text() and not args.update:
        print(f"Keeping customized dual-output notebook: {OUTPUT}")
        return

    notebook, metadata = fetch()
    version = int(metadata["currentVersionNumberNullable"])
    if LOCK.exists():
        locked = json.loads(LOCK.read_text())
        if locked["version"] != version and not args.update:
            raise SystemExit(
                f"Upstream changed from v{locked['version']} to v{version}; "
                "inspect it and rerun with --update."
            )

    # Upstream cell 0 defines its defaults. Place our overrides immediately
    # after it and before any imports/config values are consumed.
    notebook["cells"].insert(1, preset_cell(version))
    isolate_final_prediction_output(notebook)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n")
    LOCK.write_text(json.dumps({"kernel": KERNEL, "version": version, "api_url": API_URL}, indent=2) + "\n")
    print(f"Wrote {OUTPUT} from {KERNEL} v{version}")


if __name__ == "__main__":
    main()
