#!/usr/bin/env python3
"""Pin the public kimi-notebook-v17 harmonic-fusion stack for scored reruns.

Upstream: yunusgmsoy/kimi-notebook-v17 (all-in variant of the 0.913 dual-seed
baseline): harmonic forward/reverse association fusion (weight 0.30), widened
safe-division radii with divergence + mutual-NN gating, DeepCenter best.pt
(epoch 2) gap/safe-div vetoes, frame-retention guard, and a held-out train
validator. This script pins the upstream version, strips notes, fixes one
misleading guard log line, and injects a local preset that disables the
train-validator for scored reruns (it doubles GPU time without changing
submission.csv; re-enable with BIOHUB_VALIDATOR_ENABLE=1).
"""

from __future__ import annotations

import argparse
import io
import json
import re
import tokenize
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KERNEL = "yunusgmsoy/kimi-notebook-v17"
API_URL = f"https://www.kaggle.com/api/v1/kernels/pull/{KERNEL}"
OUTPUT = ROOT / "notebooks" / "biohub_harmonic_fusion_v17.ipynb"
LOCK = ROOT / "harmonic_fusion_v17.lock.json"
CJK = re.compile(r"[\u3040-\u30ff\u3400-\u9fff]")

REQUIRED_ATTACHMENTS = (
    "biohub-cell-tracking-during-development",
    "pilkwang/biohub-tracking-support-pack-50ep-v1",
    "pilkwang/biohub-temporal-unet3d-seed314159-v1",
    "pilkwang/biohub-deepcenter-unet3d-center-prior-v1",
)


def cell_source(cell: dict) -> str:
    source = cell.get("source", "")
    return "".join(source) if isinstance(source, list) else source


def set_cell_source(cell: dict, text: str) -> None:
    cell["source"] = text.splitlines(keepends=True)


def validate_notebook(notebook: dict) -> None:
    """Reject any upstream notebook that is not the expected fusion stack."""
    source = "\n".join(cell_source(cell) for cell in notebook["cells"])
    required = (
        # dual-seed ensemble inputs and runtime knobs
        "biohub-temporal-unet3d-seed314159-v1",
        "biohub-tracking-support-pack-50ep-v1",
        "BIOHUB_SECONDARY_DETECTION_WEIGHT",
        "secondary_detection_weight",
        # harmonic bidirectional fusion (the headline change)
        "BIOHUB_BIDIRECTIONAL_EDGE_WEIGHT",
        "harmonic_probability",
        # deepcenter vetoes pinned to best.pt epoch 2
        "BIOHUB_DEEPCENTER_CHECKPOINT",
        "full_frame_center/best.pt",
        # integrity + completeness machinery
        "_support_expected_manifest_sha256",
        "Support repo manifest checksum mismatch",
        "missing_datasets",
        "Retention-guard submission schema changed",
        # validator hook the preset toggles
        "BIOHUB_VALIDATOR_ENABLE",
    )
    missing = [needle for needle in required if needle not in source]
    if missing:
        raise RuntimeError(f"Unexpected upstream notebook; missing {missing}")
    # The fusion mode must be harmonic probability and the weight guard must
    # pin exactly 0.30 in both the config guard and the patch-time assertion.
    if '"BIOHUB_BIDIRECTIONAL_FUSION_MODE"] = "harmonic_probability"' not in source:
        raise RuntimeError("Upstream fusion mode is not harmonic_probability")
    if '"BIOHUB_BIDIRECTIONAL_EDGE_WEIGHT": 0.30,' not in source or (
        "_bidirectional_weight_guard, 0.30, rel_tol=0.0" not in source
    ):
        raise RuntimeError("Upstream bidirectional weight guard is not 0.30")


def strip_notebook_notes(notebook: dict) -> None:
    cells = []
    for cell in notebook["cells"]:
        if cell.get("cell_type") == "markdown":
            continue
        source = cell_source(cell)
        tokens = tokenize.generate_tokens(io.StringIO(source).readline)
        source = tokenize.untokenize(
            token for token in tokens if token.type != tokenize.COMMENT
        )
        source = source.replace(")  # (1, n_src, n_tgt)", ")")
        set_cell_source(cell, CJK.sub("", source))
        cells.append(cell)
    notebook["cells"] = cells


def fix_guard_print(notebook: dict) -> None:
    """Upstream logs 0.200 while the guarded value is 0.30; align the log."""
    for cell in notebook["cells"]:
        source = cell_source(cell)
        if "Reverse-time association weight: 0.200" in source:
            source = source.replace(
                "Reverse-time association weight: 0.200",
                "Reverse-time association weight: 0.300",
                1,
            )
            set_cell_source(cell, source)
            return
    raise RuntimeError("Guard log line not found; upstream layout changed")


def preset_cell(version: int) -> dict:
    lines = [
        "# Local reproducible preset; generated by"
        " scripts/sync_harmonic_fusion_v17.py\n",
        "import os\n",
        "from pathlib import Path\n",
        "\n",
        "# Fail fast before any setup work if a required Kaggle input is missing.\n",
        "_REQUIRED_INPUTS = {\n",
        "    'competition data': [\n",
        "        '/kaggle/input/competitions/biohub-cell-tracking-during-development',\n",
        "        '/kaggle/input/biohub-cell-tracking-during-development',\n",
        "    ],\n",
        "    'pilkwang/biohub-tracking-support-pack-50ep-v1': [\n",
        "        '/kaggle/input/biohub-tracking-support-pack-50ep-v1',\n",
        "        '/kaggle/input/datasets/pilkwang/biohub-tracking-support-pack-50ep-v1',\n",
        "    ],\n",
        "    'pilkwang/biohub-temporal-unet3d-seed314159-v1': [\n",
        "        '/kaggle/input/biohub-temporal-unet3d-seed314159-v1',\n",
        "        '/kaggle/input/datasets/pilkwang/biohub-temporal-unet3d-seed314159-v1',\n",
        "    ],\n",
        "    'pilkwang/biohub-deepcenter-unet3d-center-prior-v1': [\n",
        "        '/kaggle/input/biohub-deepcenter-unet3d-center-prior-v1',\n",
        "        '/kaggle/input/datasets/pilkwang/biohub-deepcenter-unet3d-center-prior-v1',\n",
        "    ],\n",
        "}\n",
        "_missing_inputs = [\n",
        "    label\n",
        "    for label, candidates in _REQUIRED_INPUTS.items()\n",
        "    if not any(Path(path).exists() for path in candidates)\n",
        "]\n",
        "if _missing_inputs:\n",
        "    raise RuntimeError(\n",
        "        'Missing Kaggle inputs; use + Input and attach each item, then "
        " rerun: ' + ', '.join(_missing_inputs)\n",
        "    )\n",
        "print('Required Kaggle inputs present:', len(_REQUIRED_INPUTS))\n",
        "\n",
        "BIOHUB_PRESET = 'kimi_v17_harmonic_allin'\n",
        "BIOHUB_SCORE_AXIS = ('kimi-notebook-v17 all-in over the fixed-90"
        " dual-seed 0.913 baseline: harmonic fusion 0.30, wide safe-div with"
        " divergence+mutual-NN gating, DeepCenter best.pt vetoes,'\n"
        "                   ' retention guard')\n",
        f"BIOHUB_UPSTREAM_KERNEL = {KERNEL!r}\n",
        f"BIOHUB_UPSTREAM_VERSION = {version}\n",
        "# The held-out train validator doubles scored-rerun GPU time and\n",
        "# never touches submission.csv. Keep it off for leaderboard runs;\n",
        "# set BIOHUB_VALIDATOR_ENABLE=1 to audit with the official metric.\n",
        "os.environ['BIOHUB_VALIDATOR_ENABLE'] = '0'\n",
        "print('Biohub harmonic-fusion preset loaded:',"
        " BIOHUB_UPSTREAM_KERNEL, 'v', BIOHUB_UPSTREAM_VERSION)\n",
    ]
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


def require_preset_disables_validator(notebook: dict) -> None:
    source = "\n".join(cell_source(cell) for cell in notebook["cells"][:1])
    if "BIOHUB_VALIDATOR_ENABLE'] = '0'" not in source and (
        'BIOHUB_VALIDATOR_ENABLE"] = "0"' not in source
    ):
        raise RuntimeError("Preset cell must disable the validator for scored runs")


def require_input_guard(notebook: dict) -> None:
    source = "".join(cell_source(cell) for cell in notebook["cells"][:1])
    for needle in ("_REQUIRED_INPUTS", "Missing Kaggle inputs"):
        if needle not in source:
            raise RuntimeError(f"Preset input guard missing {needle!r}")
    for item in REQUIRED_ATTACHMENTS[1:]:
        if f"'{item}': [" not in source.replace('"', "'") and (
            f'"{item}": [' not in source
        ):
            raise RuntimeError(f"Preset input guard missing dataset {item!r}")


def build(notebook: dict, version: int) -> dict:
    validate_notebook(notebook)
    strip_notebook_notes(notebook)
    fix_guard_print(notebook)
    notebook["cells"].insert(0, preset_cell(version))
    require_preset_disables_validator(notebook)
    require_input_guard(notebook)
    return notebook


def fetch() -> tuple[dict, dict]:
    request = urllib.request.Request(API_URL, headers={"User-Agent": "biohub-fusion/1"})
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.load(response)
    return json.loads(payload["blob"]["source"]), payload["metadata"]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--update", action="store_true", help="accept a newer upstream version"
    )
    args = parser.parse_args()

    notebook, metadata = fetch()
    version = int(metadata["currentVersionNumberNullable"])
    if LOCK.exists() and not args.update:
        locked = json.loads(LOCK.read_text())
        if locked["version"] != version:
            raise SystemExit(
                f"Upstream changed from v{locked['version']} to v{version}; "
                "inspect then use --update."
            )

    notebook = build(notebook, version)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n")
    LOCK.write_text(
        json.dumps({"kernel": KERNEL, "version": version, "api_url": API_URL}, indent=2)
        + "\n"
    )
    print(f"Wrote {OUTPUT} from {KERNEL} v{version}")


if __name__ == "__main__":
    main()
